// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuqhfeicfrpfahtrsnsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cWhmZWljZnJwZmFodHJzbnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTcxMjYsImV4cCI6MjA2MDkzMzEyNn0.wMG1Z9q6qpfdCgvIAf6hWcSewpJkC1EQLxXnkA3YmNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);